### ISSUE TITLE
Getting SessionExpired Exception

### ISSUE THREAD

**Issue by SohamKukreti** [codelif/pyjiit#5]
Da api is returning session expired exception. Temporarily fixed by commenting out 2 lines:
```
    @wraps(method)
    def wrapper(self, *args, **kwargs):
        if self.session is None:
            raise NotLoggedIn

        # if self.session.expiry < datetime.now():
        #     raise SessionExpired

        return method(self, *args, **kwargs)
    wrapper.__doc__ = method.__doc__
    return wrapper
```
a permanent solution would be fire :fire:

**Comment by codelif** [comment]
lemme check in an hour or so

**Comment by codelif** [comment]
Ok, so this is kinda weird. The college's webportal api is returning wrong timestamps for cookie issue and expiry. IDK the reason behind it, but due to this their website is also broken. 

There is usually a prompt when the cookie is about to expire on their website, which doesn't seem work now (because of this bug)

So, our previous naive approach wouldn't work. A fix would be to raise this exception in `__hit` method, for if the JSON returns Unauthorized like this:
![image](https://github.com/user-attachments/assets/b703cda9-9283-485b-a5d1-ca743e0059d6)


Otherwise please suggest if you have something else in mind?

**Comment by codelif** [comment]
I have this commit ready, if you are okay with this, then I will merge it.

**Comment by codelif** [comment]
Also, thanks for highlighting this issue. I had to replace this check with something robust like above anyway, since this check was a race-condition.

**Comment by codelif** [comment]
This is probably ok, continue this thread if you have any issue.

**Comment by codelif** [comment]
I have published the release you can update your versions as well : `pip install --upgrade pyjiit`

**Comment by codeblech** [comment]
merged changes look good

> So, our previous naive approach wouldn't work.

which approach though?

**Comment by codelif** [comment]
> which approach though?

Checking the session expiry against current time.

Since the server itself returns incorrect timestamps.


p.s. Also, it seems I mistakenly Edited your comment (idk why GitHub allows that smh). I reverted it now.

**Comment by codeblech** [comment]
> Also, it seems I mistakenly Edited your comment (idk why GitHub allows that smh). I reverted it now.

that's hilarious xD. I'll try that sometime 🤣
